---
services:
  gateway:
    image: inductiveautomation/ignition:8.3.1
    ports:
      - "8088:8088"
    volumes:
      - ./services/ignition/config:/usr/local/bin/ignition/data/config 
      - ./services/ignition/projects:/usr/local/bin/ignition/data/projects
      - ./shared/gateway-utilities/projects/gateway-utilities:/usr/local/bin/ignition/data/projects/gateway-utilities
      # Temporary volume to skip commissioning
      - ./services/ignition/commissioning.json:/usr/local/bin/ignition/data/commissioning.json
    environment:
      IGNITION_EDITION: "standard"
      DISABLE_QUICKSTART: "true"
      ACCEPT_IGNITION_EULA: "Y"
      GATEWAY_MODULES_ENABLED: |
        com.inductiveautomation.eventstream,
        com.inductiveautomation.historian,
        com.inductiveautomation.perspective,
        com.inductiveautomation.jdbc.postgresql,
        com.inductiveautomation.webdev,
        com.inductiveautomation.opcua
    command: >
      -n ignition83
      --
      -Dignition.config.mode=local-dev
    labels:
      traefik.enable: "true"
      traefik.http.routers.ignition.rule: "Host(`ignition83.localtest.me`)"
      traefik.http.routers.ignition.entrypoints: "websecure"
      traefik.http.services.ignition.loadbalancer.server.port: "8088"
    networks:
      - default
      - proxy

  database:
    image: postgres
    hostname: postgres
    volumes:
      - ./services/postgres/init-sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: P@ssword1!
      POSTGRES_USER: postgres
    
  liquibase:
    image: liquibase/liquibase
    depends_on:
      - database
    volumes:
      - ./services/postgres:/database
      - ./services/postgres/postgresql.jar:/liquibase/lib/postgresql.jar
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
    entrypoint: ["/wait-for-it.sh", "postgres:5432", "--", "liquibase", "--defaultsFile=/database/liquibase/liquibase.docker.properties", "update"]
  
  # Uncomment the following lines to enable pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./services/pgadmin/servers.json:/pgadmin4/servers.json
    labels:
      traefik.enable: "true"
      traefik.http.routers.pgadmin.rule: "Host(`postgres-pgadmin.localtest.me`)"
      traefik.http.routers.pgadmin.entrypoints: "websecure"
      traefik.http.services.pgadmin.loadbalancer.server.port: "80"
    networks:
      - default
      - proxy

  proxy:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8090:8080"  # Traefik dashboard (direct access)
    environment:
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:443
      - TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS=true
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_API_INSECURE=true
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_PROVIDERS_DOCKER_NETWORK=proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.proxy.rule: "Host(`proxy.localtest.me`)"
      traefik.http.routers.proxy.entrypoints: "websecure"
      traefik.http.routers.proxy.service: "api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy